add multi view
fix multiplier speed

only spectate in free-view

dont active multi view and follow mode and t0

fix lagging, tweak mutiplier and zoom

be able to spectate tees in /spec too

add multi view

added death players are getting removed from id

changed smth

fix unused

Update gameclient.cpp

use std::any_of

Revert "add m (#40)"

This reverts commit 0153a52dfe3ccba4498857b484d8bc473d7d0603.

add m (#40)

* Don't count (connecting) players for voting

* Clear editor file browser search term when entering folder

Closes #5620.

* Refactor demo seekbar width calculation

* Add tooltip to demo seekbar showing the currently hovered time

When hovering the demo seekbar, show a tooltip with the time at the hovered position.

* Fix build with clang on debian 11

$ clang --version
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Fixes this error

```
In file included from
/home/chiller/Desktop/git/ddnet/src/base/color.h:6:
/home/chiller/Desktop/git/ddnet/src/base/vmath.h:141:38: error:
constexpr function never produces a constant expression
[-Winvalid-constexpr]
constexpr inline vector2_base<float> direction(float angle)
                                     ^
/home/chiller/Desktop/git/ddnet/src/base/vmath.h:143:29: note:
non-constexpr function 'cosf' cannot be used in a constant expression
        return vector2_base<float>(cosf(angle), sinf(angle));
                                   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:62:1: note: declared here
__MATHCALL_VEC (cos,, (_Mdouble_ __x));
^
/usr/include/math.h:266:3: note: expanded from macro '__MATHCALL_VEC'
  __MATHCALL (function, suffix, args)
  ^
/usr/include/math.h:273:3: note: expanded from macro '__MATHCALL'
  __MATHDECL (_Mdouble_,function,suffix, args)
  ^
/usr/include/math.h:275:3: note: expanded from macro '__MATHDECL'
  __MATHDECL_1(type, function,suffix, args); \
  ^
/usr/include/math.h:283:15: note: expanded from macro '__MATHDECL_1'
  extern type __MATH_PRECNAME(function,suffix) args __THROW
              ^
/usr/include/math.h:303:34: note: expanded from macro '__MATH_PRECNAME'
                                 ^
<scratch space>:34:1: note: expanded from here
cosf
^
1 error generated.
make[2]: *** [CMakeFiles/engine-shared.dir/build.make:173:
CMakeFiles/engine-shared.dir/src/engine/shared/console.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:604:
CMakeFiles/engine-shared.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

* Fix layout of kick/spec vote list items

The tee and label were overlapping due to a regression from #6240.

* Ensure integer wrapping instead of preventing overflow/underflow

As the integer overflow/underflow in `UndiffItem` can happen during normal gameplay, we should in this case neither ignore the snapshot delta nor show an error message.

Instead of depending on the particular compiler doing integer wrapping, when integer overflows or underflows occur, we make it part of the design, by casting to `unsigned`, which ensures that integer wrapping is being used.

* Improve `str_hex` documentation

* Add `str_hex_cstyle` to print bytes as a C style array

This function converts data to a C style array string presentation.

* Fix `sv_vanilla_antispoof` for vanilla 0.6.5 clients

This fixes issues that prevented vanilla 0.6.5 clients from joining DDNet servers with `sv_vanilla_antispoof 1` (closes #2074).

The dummy map was not valid. The size of the tiles and game layers was calculated incorrectly. The last member variable included in `CMapItemLayerTilemap` version 2 should be `m_Data`. Previously only the size of the member `m_aName` was subtracted from the total size, which was resulting in an incorrect item size, as the size of the following 5 members also needs to be subtracted.

The handshake messages were packed incorrectly. The message ID and the system flag were not added to the six packers that are passed to `SendMsgs`. The lines that are removed in this function seemed to assume that the message ID was already added but not packed, which was no longer the case. Presumable at some point `CMsgPacker` was changed without adapting the vanilla antispoof feature. Now, the message ID and system flag are properly packed when initially creating the message packers.

The `dummy_map` tool is improved to also print the generated map file's hashes and data as a C style array, so the data can immediately be copied to `network_server.cpp`.

* Version 16.7.2

* `CMsgPacker` doesn't know about message ID encoding

CC #6289

* Minor refactoring of `CFifo`

- Remove unused include.
- Instead of quitting entirely, only disable the fifo component when file cannot be used.
- Return early to reduce indentation.

* Export `windows_format_system_message` utility on Windows

Declare the function in `system.h`, so we can use it in other platform-specific components.

* Implement FIFO on Windows using Named Pipes

Reimplement the Linux FIFO file server and client controls on Windows by using Named Pipes.

The DDNet server/client acts as a named pipe server and receives messages.
Messages can be posted to the named pipe server by connecting to it as a client.
The named pipe client can for instance be controlled from the command line with PowerShell.

The PowerShell script `scripts/send_named_pipe.ps1` is added for this purpose.
For example the PowerShell command `./send_named_pipe.ps1 "testpipe" "echo a"` sends the command `echo a` to the pipe named `testpipe`.
Multiple commands can be sent at the same time by separating them with semicolons or newlines.

* Add `CLayer::IsEntitiesLayer` to reduce duplicate code

* Remove dead code, update documentation for `LAYERTYPE_GAME`

This layer type was never used when saving maps.
Game layers were always identified by their flags.
In any case the check in the popup handler is unnecessary, as the group property cannot be changed for game layers, so this code is never used.

* Refactor `CEditor:::PopupLayer`, remove `CEditor::IsSpecialLayer`

- Use `pCurrentLayer` instead of `pEditor->GetSelectedLayer(0)` everywhere.
- Remove unnecessary null-checks of `pCurrentLayer`.
- Use `CLayer::IsEntitiesLayer` instead of `CEditor::IsSpecialLayer` and remove the latter function.
- Restructure UI layout code and variables.

* Use doxygen style for all `fs_*` functions

* Add `fs_is_file` to check if a given path is file

* Add `IStorage::FileExists` and `IStorage::FolderExists`

As wrappers around `fs_is_file` and `fs_is_dir`.

* Show error message when downloaded map cannot be saved

Check if deleting the old map file or renaming the temporary downloaded map fails. If so, show an error message which indicates that the user should delete the map file manually.

Sometimes downloaded map files seem to end up with wrong permissions, ownership or with read-only flag set, which makes the client unable to delete them.

* More minimal clang-tidy 15 run

Alternative to #6294

The only remaining problems are:
/home/deen/git/ddnet/src/engine/client/backend/glsl_shader_compiler.cpp:22:26: warning: unnecessary temporary object created while calling emplace_back [modernize-use-emplace]
        m_vDefines.emplace_back(SGLSLCompilerDefine(DefineName, DefineValue));
                                ^~~~~~~~~~~~~~~~~~~~                       ~

* Use OpenGL 3.3 on macOS by default

Otherwise falls back to OpenGL 1.5, since 3.0 is not supported

* Fix map check excluded warnings in CI

Due to changes in wording of the error messages, some of the twmap-check-ddnet warnings were no longer suppressed.

Closes #6305.

* Fix Crash in CSafeTeam::Safe/Load

Fixes #6304

`pEnt` is freed after removing, so must not be used in the next loop
iteration.

* Add tooltip support for editboxes in editor

Add tooltips for envelope name, point value and point time.

* Pass `nullptr` to `CUIRect` functions when result is unused

* Rename envelope `Synchronized` checkbox to `Sync.`

To gain more width of other controls.

* Use `IGraphics::CORNER_NONE` instead of `0`

* Remove dead commented code

* Remove unnecessary temporary `CUIRect`

* Add margin to point value/time editboxes for low screen width

The labels for the editboxes are not shown when the screen width is low, but the spacing should still be applied to the editboxes in that case.

* Add `CEnvPoint::MAX_CHANNELS` constant

* Reserve same space for all envelope channel buttons

Keep all the UI elements in the envelope editor at the same position, independent from the number of channels of the selected envelope.

Previously the UI elements changed their position due to different numbers of channels of the different envelope types. Now the space for the maximum number of channels is always reserved and the UI elements don't move around.

* Align the editbox labels in the envelope editor with the editboxes

* Slightly decrease width of name editbox if total width is low

* Decrease buffer size

* Add buttons to move envelopes left and right, use unicode icons

Closes #4129.

* Only use pthread_attr_set_qos_class_np if it's available

Noticed in nixOS that DDNet package is marked as broken on Darwin for this reason:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/ddnet/default.nix

* Fix Persian language crash (fixes #6310)

* Fix division by zero when joystick deadzone is at maximum

By preventing the actual deadzone value from reaching `1.0f`.

* Use `bool` instead of `int` for `m_InputGrabbed`

* Remove unused `IInput::VideoRestartNeeded`

The variable is never set to `true` so the function always returns `false` and any code depend on this variable was never executed.

* Disable relative joystick when console is open or window not focused

It shouldn't be possible to move the joystick when the console is open or when the window is not focused.

* Increase relative joystick movement based on input update time

For relative mouse movement in SDL, the `SDL_GetRelativeMouseState` function always returns distance that the mouse moved since the last call of this function.

For joysticks, we only have access to the current axis values and no accumulated values.
This made the relative joystick movement speed decrease a lot when the client's refresh rate is low.
This is now counteracted by measuring the average time between calls of `IInput::Update` and multiplying the joystick movement by this number.

Closes #6296.

* Replace unnecessary `char` buffers with pointers

* Print database connection error that was previously unused

The string copied into `aError` was previously unused because the function immediately returns.

Now the error is logged to the console.

* Fix empty chat message being sent when using `moderate`

When activating `moderate` on a server that already has another active moderator, `aBuf` contained undefined values and the empty or undefined message was sent to the clients.

Clients ignore empty chat messages and don't display or log them, but the empty message can be seen in the server console.

Now no buffer is used anymore, so no empty message can be sent.

* Use `str_copy` instead of `str_format`

Using `str_format` without format arguments is equivalent to `str_copy`, but using the latter is more efficient and readable.

As `str_format` also returns the result `str_utf8_fix_truncation`, i.e. the potentially truncated string length, the return value is also added to `str_copy` so existing invocations don't need to be adjusted.

---------

Co-Authored-By: def <dennis@felsin9.de>
Co-Authored-By: Robert Müller <robytemueller@gmail.com>
Co-Authored-By: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Co-Authored-By: ChillerDragon <chillerdragon@gmail.com>
Co-Authored-By: heinrich5991 <heinrich5991@gmail.com>
Co-Authored-By: Zwelf <zwelf@strct.cc>